name: Wyoming Cloudflare Bridge
version: "1.0.1"
slug: wyoming-cloudflare-bridge
description: Wyoming Protocol bridge to Cloudflare Workers AI for Speech-to-Text and Text-to-Speech
url: https://github.com/KJegen149/wyoming-cloudflare-bridge
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
startup: services
host_network: true
ports:
  10300/tcp: 10300
ports_description:
  10300/tcp: Wyoming Protocol server port
options:
  stt_url: ""
  tts_url: ""
  log_level: INFO
schema:
  stt_url: str
  tts_url: str
  log_level: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)?
